services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
      - 5555:5555
    environment:
      - LOCAL_DB=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  test:
    container_name: test
    build:
      context: .
      dockerfile: ./apps/test/Dockerfile
    restart: always
    ports:
      - 8000:8000
    environment:
      - LOCAL_DB=postgresql://postgres:postgres@db:5432/postgres

volumes:
  postgres-data:
    external: false
