services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - web_network
    environment:
      - LOCAL_DB=postgresql://postgres:postgres@xlx-db:5432/postgres
    depends_on:
      - db
      - migrate
        
  migrate:
    image: node:alpine
    container_name: migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./packages/xlx-db:/app/packages/xlx-db
    entrypoint: ["sh", "-c", "apk add --no-cache postgresql-client && until pg_isready -h xlx-db -U postgres; do sleep 1; done; npx prisma migrate dev --schema=/app/packages/xlx-db/prisma/schema.prisma"]
    environment:
      - LOCAL_DB=postgresql://postgres:postgres@xlx-db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  db:
    image: postgres:alpine
    container_name: xlx-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  web_network:
    external: true

volumes:
  postgres-data:
    external: false
